2023-10-30 14:22:29,592 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-30 14:22:29,592 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Configure stats pid to 119476
2023-10-30 14:22:29,592 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Loading settings from /home/henry/.config/wandb/settings
2023-10-30 14:22:29,592 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Loading settings from /home/henry/Documents/BCI/wandb/settings
2023-10-30 14:22:29,592 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-30 14:22:29,592 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'training.py', 'program_abspath': '/home/henry/Documents/BCI/training.py', 'program': '/home/henry/Documents/BCI/training.py'}
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_init.py:_log_setup():528] Logging user logs to /home/henry/Documents/BCI/wandb/run-20231030_142229-srlxrj8b/logs/debug.log
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_init.py:_log_setup():529] Logging internal logs to /home/henry/Documents/BCI/wandb/run-20231030_142229-srlxrj8b/logs/debug-internal.log
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_init.py:init():568] calling init triggers
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_init.py:init():618] starting backend
2023-10-30 14:22:29,593 INFO    MainThread:119476 [wandb_init.py:init():622] setting up manager
2023-10-30 14:22:29,597 INFO    MainThread:119476 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-30 14:22:29,600 INFO    MainThread:119476 [wandb_init.py:init():628] backend started and connected
2023-10-30 14:22:29,603 INFO    MainThread:119476 [wandb_init.py:init():720] updated telemetry
2023-10-30 14:22:29,607 INFO    MainThread:119476 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-30 14:22:29,805 ERROR   MainThread:119476 [wandb_init.py:init():779] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-10-30 14:22:30,203 ERROR   MainThread:119476 [wandb_init.py:init():1188] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/home/henry/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/henry/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-10-30 14:22:31,248 WARNING MsgRouterThr:119476 [router.py:message_loop():77] message_loop has been closed
