Traceback (most recent call last):
  File "/home/henry/Documents/BCI/training.py", line 154, in <module>
    main()
  File "/home/henry/Documents/BCI/training.py", line 28, in main
    out_layers = [wandb.config["a"], wandb.config["b"], wandb.config["c"]]
                  ~~~~~~~~~~~~^^^^^
  File "/home/henry/.local/lib/python3.11/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'a'
Traceback (most recent call last):
  File "/home/henry/Documents/BCI/training.py", line 154, in <module>
    main()
  File "/home/henry/Documents/BCI/training.py", line 28, in main
    out_layers = [wandb.config["a"], wandb.config["b"], wandb.config["c"]]
                  ~~~~~~~~~~~~^^^^^
  File "/home/henry/.local/lib/python3.11/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'a'